version: '3.1'
services:
    nginx:
        image: 'nginx:latest'
        restart: always
        expose:
            - 80
        volumes:
            - '../src/:/code'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        environment:
            VIRTUAL_HOST: example.mystery.digital
            LETSENCRYPT_HOST: example.mystery.digital
            LETSENCRYPT_EMAIL: example@mystery.digital

    php:
        image: php:7.3-fpm
        volumes:
            - '../src:/code'
            - './php/php.ini:/usr/local/etc/php/conf.d/php_extra.ini'
        environment:
            PHP_INI_DIR: /usr/local/etc/php/conf.d
        container_name: php

networks:
    default:
        external:
            name: nginx-proxy
